### PR TITLE
Metis fine

### PR DESCRIPTION
**Pull request by l-kotzur**

### CODE REVIEW

**Comment by l-kotzur** [comment]
Build is failing since anaconda is taking too long to get the requirements: @k-knosala @t-gross Didn't we switch to mamba?

**Comment by l-kotzur** [comment]
> Build is failing since anaconda is taking too long to get the requirements: @k-knosala @t-gross Didn't we switch to mamba?

Obviously. Just need to take the gitlab-ci code.

**Comment by k-knosala** [comment]
Oh yes, I did not have a look at the travis.yml when switching.

**Comment by t-gross** [comment]
I fixed the travis.yml (use of the correct environment name). Tests are successful, now. 
Thanks @l-kotzur for adapting!

**Comment by l-kotzur** [comment]
@t-gross @Shruthi-Patil Which ToDos are open such that we can merge?

**Comment by Shruthi-Patil** [comment]
@l-kotzur there is a [bug in the netcdf feature](https://jugit.fz-juelich.de/iek-3/shared-code/fine/-/issues/216) that needs fixing. Apart from that we're good to go

**Comment by t-gross** [comment]
Changes are updated in another branch for next FINE release.

**Pull request closed without merging**
